server:
  port: 8080

spring:
  application:
    name: stock-service
  datasource:
    # mysql config 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://138.197.82.121:3306/nci-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 5dtMqZTwbeir515Y